### ISSUE TITLE
如何使用啊 大神

### ISSUE THREAD

**Issue by dungang** [lh4111/ionic-jpush#1]
`      this.jpush.init()
      .then(res => alert(res))
      .catch(error => alert(error));
`
这样使用 没有注册成功

**Comment by lh4111** [comment]
@dungang 
 不需要init `this.jpush.init()`

已经更新README.md了
用法和其他官方插件一样

**Comment by dungang** [comment]
谢谢！

**Comment by CK110** [comment]
@lh4111 为什么不需要init？

**Comment by lh4111** [comment]
@CK110 应该是默认自动开启推送的
