### ISSUE TITLE
可不可以提供ts源码版本？

### ISSUE THREAD

**Issue by CK110** [lh4111/ionic-jpush#3]

**Comment by lh4111** [comment]
有时间我放在wiki里面写如何使用官方的@ionic-native工具生成吧，放在代码仓库里面很臃肿

**Comment by lh4111** [comment]
@CK110 [ts源文件](https://github.com/lh4111/ionic-jpush/wiki/.ts-%E6%BA%90%E6%96%87%E4%BB%B6)
