### ISSUE TITLE
按照Readme步驟做一遍但沒有任何反應

### ISSUE THREAD

**Issue by waltermak** [lh4111/ionic-jpush#5]
我根據README的方法做，但是沒有 return regid。我也嘗試了 catch error，但是甚麼都沒有。
我現在的配置是這樣的，請替我看看，謝謝。

cli packages: 

    @ionic/cli-utils  : 1.10.2
    ionic (Ionic CLI) : 3.10.3

global packages:

    Cordova CLI : 7.0.1

local packages:

    @ionic/app-scripts : 2.0.2
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.5.3

System:

    Node : v6.11.1
    npm  : 3.10.10
    OS   : Windows 10

**Comment by lh4111** [comment]
解决了吗

**Comment by waltermak** [comment]
解决了! 只是我編得不好 謝謝你 👍
